version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - aws configure set aws_role_arn $AWS_ROLE_ARN 

  pre_build:
      
  build:
    commands:
      - docker build -t public.ecr.aws/bitnami/kaniko:latest

  post_build:

cache:
  paths:
    - /root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/

artifacts:
  paths:
    - argo.txt