version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip3 install awscli nltk numpy
      
  pre_build:
    commands:
      - aws configure set aws_role_arn $AWS_ROLE_ARN
      
  build:
    commands:
      - aws s3 cp s3://ddarwin/oak.txt oak.txt
      - python3 intro.py > dove.txt
      
  post_build:
    commands:
      - aws s3 cp dove.txt s3://ddarwin/dove.txt
