RUN mkdir /oanc/nltk_cache

COPY --from=builder /oanc/nltk_cache /oanc/nltk_cache

RUN pip install --no-cache-dir --no-index-url nltk[$NLTK_DOWNLOAD] numpy awscli || true

COPY --from=builder /oanc/nltk_cache /oanc/nltk_cache